#!/usr/bin/env python3
"""Generate the Home Free handshake cross-implementation test vectors.

Emits ``web/src/homefree/handshake.vectors.json`` from the Python reference
implementation, using pinned ephemeral keys so the fixture is deterministic. The
browser (WebCrypto) mirror and the Python drift-guard test both assert against
this fixture, proving byte-for-byte interoperability.

Run from the repo root:  ``python3 scripts/gen_homefree_vectors.py``
"""

from __future__ import annotations

import json
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey

from agent_sessions.homefree.handshake import Initiator, Responder, derive_psk

FIXTURE = Path("web/src/homefree/handshake.vectors.json")

ACCESS_KEY = "HOMEFREE-VECTOR-KEY-v1"
I_EPH_SEED = bytes.fromhex("01" * 32)
R_EPH_SEED = bytes.fromhex("02" * 32)
I2R_PLAINTEXTS = [b"hello from the browser\n", b"ls -la /etc\n"]
R2I_PLAINTEXTS = [b"total 4\ndrwxr-xr-x  2 root root\n", b"pty output chunk 2"]


def build_vectors() -> dict:
    psk = derive_psk(ACCESS_KEY)
    ini = Initiator(psk, _ephemeral=X25519PrivateKey.from_private_bytes(I_EPH_SEED))
    res = Responder(psk, _ephemeral=X25519PrivateKey.from_private_bytes(R_EPH_SEED))

    e_i = ini.start()
    msg2 = res.respond(e_i)
    t_ini, msg3 = ini.finish(msg2)
    t_res = res.finish(msg3)

    i2r = []
    for pt in I2R_PLAINTEXTS:
        frame = t_ini.encrypt(pt)
        assert t_res.decrypt(frame) == pt  # sanity: responder decrypts it
        i2r.append({"plaintext_hex": pt.hex(), "frame_hex": frame.hex()})

    r2i = []
    for pt in R2I_PLAINTEXTS:
        frame = t_res.encrypt(pt)
        assert t_ini.decrypt(frame) == pt  # sanity: initiator decrypts it
        r2i.append({"plaintext_hex": pt.hex(), "frame_hex": frame.hex()})

    return {
        "_comment": "Generated by scripts/gen_homefree_vectors.py — do not edit by hand.",
        "access_key": ACCESS_KEY,
        "psk_hex": psk.hex(),
        "initiator_ephemeral_priv_hex": I_EPH_SEED.hex(),
        "responder_ephemeral_priv_hex": R_EPH_SEED.hex(),
        "e_i_hex": e_i.hex(),
        "e_r_hex": msg2[:32].hex(),
        "conf_r_hex": msg2[32:].hex(),
        "msg2_hex": msg2.hex(),
        "msg3_hex": msg3.hex(),
        "transport": {"i2r": i2r, "r2i": r2i},
    }


def main() -> None:
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(build_vectors(), indent=2) + "\n")
    print(f"wrote {FIXTURE}")


if __name__ == "__main__":
    main()
